import type { GrammarTarget, LearningObjective, Location, VocabularyTarget } from '../../types/objectives';
import { runtimeAssetUrl } from '@/lib/runtime-assets';

const LEVEL_0_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-script-xiaolongbao-characters',
    levelNumber: 0,
    category: 'script',
    title: 'Read the core characters',
    description: 'Recognize the characters behind 方案, 不一样, and 小笼包',
    targetItems: ['方', '案', '不', '一', '样', '愿', '意', '装', '小', '笼', '包'],
    targetCount: 11,
    assessmentThreshold: 0.8,
    prerequisites: [],
    tags: ['zh', 'script', 'characters', 'xiaolongbao', 'restaurant'],
  },
  {
    id: 'zh-script-xiaolongbao-phrases',
    levelNumber: 0,
    category: 'script',
    title: 'Read key shop phrases',
    description: 'Read the menu and scene phrases that appear around the stall',
    targetItems: ['小笼包', '不一样', '愿意', '方案'],
    targetCount: 4,
    assessmentThreshold: 0.75,
    prerequisites: ['zh-script-xiaolongbao-characters'],
    tags: ['zh', 'script', 'reading', 'menu', 'phrases'],
  },
];

const LEVEL_1_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-pron-tone-pairs',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Hear the tone pairs',
    description: 'Hear and repeat the tones in 方案 and 愿意',
    targetItems: ['方案 fāng\'àn', '愿意 yuànyì'],
    targetCount: 2,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-script-xiaolongbao-characters'],
    tags: ['zh', 'pronunciation', 'tones', 'pinyin', 'tonal-pairs'],
  },
  {
    id: 'zh-pron-zhuang-pao-drills',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Practice 装 and 跑 clarity',
    description: 'Drill the fast-shifting sounds in 装 and 跑 during vendor talk',
    targetItems: ['装', '跑'],
    targetCount: 2,
    assessmentThreshold: 0.75,
    prerequisites: ['zh-script-xiaolongbao-characters'],
    tags: ['zh', 'pronunciation', 'minimal-pairs', 'clarity', 'dialogue'],
  },
];

const LEVEL_2_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-vocab-xiaolongbao-core',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn the core shop words',
    description: 'Know the key words that appear in the stall scene',
    targetItems: ['方案', '愿意', '装', '不一样', '小笼包', '蟹壳黄', '阿姨'],
    targetCount: 7,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-pron-tone-pairs'],
    tags: ['zh', 'vocabulary', 'restaurant', 'nouns', 'scene'],
  },
  {
    id: 'zh-vocab-xiaolongbao-social',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn the social and action words',
    description: 'Use the words for stubbornness, ability, taking things on, and importance',
    targetItems: ['犟', '本事', '接', '重要'],
    targetCount: 4,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-vocab-xiaolongbao-core'],
    tags: ['zh', 'vocabulary', 'verbs', 'adjectives', 'social'],
  },
];

const LEVEL_3_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-gram-bu-hui-vs-bu-yuan-yi',
    levelNumber: 3,
    category: 'grammar',
    title: 'Use 不会 vs 不愿意',
    description: 'Distinguish inability from unwillingness in scene dialogue',
    targetItems: ['不会', '不愿意'],
    targetCount: 2,
    assessmentThreshold: 0.85,
    prerequisites: ['zh-vocab-xiaolongbao-social'],
    tags: ['zh', 'grammar', 'contrast', 'modality', 'refusal'],
  },
  {
    id: 'zh-gram-ni-register',
    levelNumber: 3,
    category: 'grammar',
    title: 'Switch between 你 and 您',
    description: 'Choose the right level of address for friends, aunties, and customers',
    targetItems: ['你', '您'],
    targetCount: 2,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-vocab-xiaolongbao-core'],
    tags: ['zh', 'grammar', 'register', 'politeness', 'address'],
  },
  {
    id: 'zh-gram-le-aspect',
    levelNumber: 3,
    category: 'grammar',
    title: 'Use the 了 aspect marker',
    description: 'Mark completed actions and state changes in the restaurant scene',
    targetItems: ['了'],
    targetCount: 1,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-vocab-xiaolongbao-core'],
    tags: ['zh', 'grammar', 'aspect', 'completion', 'state-change'],
  },
  {
    id: 'zh-gram-bu-xia-qu',
    levelNumber: 3,
    category: 'grammar',
    title: 'Use the 不下去 complement',
    description: 'Show that an action cannot keep going or cannot be carried through',
    targetItems: ['不下去'],
    targetCount: 1,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-gram-le-aspect'],
    tags: ['zh', 'grammar', 'potential-complement', 'continuation', 'difficulty'],
  },
];

export const VOCABULARY_TARGETS: VocabularyTarget[] = [
  {
    word: '小笼包',
    romanization: 'xiǎolóngbāo',
    translation: 'soup dumplings',
    category: 'food_item',
    level: 2,
    sceneContext: 'the main dish written in bold on the front menu',
    visualCue: 'bamboo steamers stacked at the counter with soup dumplings inside',
  },
  {
    word: '蟹壳黄',
    romanization: 'xièkéhuáng',
    translation: 'crab shell pastry',
    category: 'pastry',
    level: 2,
    sceneContext: 'a tray of pastries near the cashier',
    visualCue: 'golden sesame-crusted pastries piled in a metal tray',
  },
  {
    word: '方案',
    romanization: 'fāng\'àn',
    translation: 'plan / approach',
    category: 'noun',
    level: 2,
    sceneContext: 'the auntie explains a plan for the next batch of dumplings',
    visualCue: 'clipboard notes beside a steaming basket order slip',
  },
  {
    word: '愿意',
    romanization: 'yuànyì',
    translation: 'willing to',
    category: 'adjective',
    level: 2,
    sceneContext: 'used when someone agrees to help in the kitchen',
    visualCue: 'a helper nodding beside the steamer stack',
  },
  {
    word: '装',
    romanization: 'zhuāng',
    translation: 'to pack; to load',
    category: 'verb',
    level: 2,
    sceneContext: 'the dumplings are packed into a takeaway box',
    visualCue: 'a paper box being filled with a fresh basket of dumplings',
  },
  {
    word: '不一样',
    romanization: 'bù yí yàng',
    translation: 'different',
    category: 'adjective',
    level: 2,
    sceneContext: 'the cook compares this shop to every other shop in the lane',
    visualCue: 'two dumpling baskets side by side with slightly different fillings',
  },
  {
    word: '阿姨',
    romanization: 'āyí',
    translation: 'auntie / older woman',
    category: 'person',
    level: 2,
    sceneContext: 'the warm but sharp-tongued woman running the counter',
    visualCue: 'the counter auntie in an apron calling orders',
  },
  {
    word: '犟',
    romanization: 'jiàng',
    translation: 'stubborn',
    category: 'adjective',
    level: 2,
    sceneContext: 'someone refusing to change their mind about the filling',
    visualCue: 'a vendor shaking her head while pointing at the menu',
  },
  {
    word: '本事',
    romanization: 'běnshi',
    translation: 'skill; ability',
    category: 'noun',
    level: 2,
    sceneContext: 'the auntie praises real kitchen skill, not talk',
    visualCue: 'hands shaping dumpling wrappers with practiced speed',
  },
  {
    word: '接',
    romanization: 'jiē',
    translation: 'to take on; to receive',
    category: 'verb',
    level: 2,
    sceneContext: 'used when taking an order or accepting a challenge',
    visualCue: 'a hand taking a steaming basket from the wok side',
  },
  {
    word: '重要',
    romanization: 'zhòngyào',
    translation: 'important',
    category: 'adjective',
    level: 2,
    sceneContext: 'the auntie stresses what matters most in the kitchen',
    visualCue: 'a note pinned above the steamer: freshness first',
  },
];

export const GRAMMAR_TARGETS: GrammarTarget[] = [
  {
    id: 'zh-gram-bu-hui-vs-bu-yuan-yi',
    pattern: '不会 vs 不愿意',
    explanation: '不会 means not able to do something. 不愿意 means not willing to do it. The difference is ability versus attitude.',
    examples: [
      { target: '我不会包小笼包。', translation: 'I do not know how to wrap xiaolongbao.' },
      { target: '我不愿意等太久。', translation: 'I am not willing to wait too long.' },
      { target: '他不会来，但他也不愿意解释。', translation: 'He cannot come, but he also does not want to explain.' },
    ],
    level: 3,
    locationId: 'xiaolongbao',
  },
  {
    id: 'zh-gram-ni-register',
    pattern: '你 / 您',
    explanation: '你 is informal and direct. 您 is the polite, respectful form for customers, elders, and strangers.',
    examples: [
      { target: '你要几个？', translation: 'How many do you want?' },
      { target: '您先坐。', translation: 'Please sit first.' },
      { target: '你来试试。', translation: 'You try it.' },
    ],
    level: 3,
    locationId: 'xiaolongbao',
  },
  {
    id: 'zh-gram-le-aspect',
    pattern: '了',
    explanation: '了 marks a completed action or a new state. It often shows that something has just happened or is now true.',
    examples: [
      { target: '我买了两笼。', translation: 'I bought two baskets.' },
      { target: '小笼包好了。', translation: 'The xiaolongbao is ready.' },
      { target: '阿姨开始忙了。', translation: 'Auntie has gotten busy.' },
    ],
    level: 3,
    locationId: 'xiaolongbao',
  },
  {
    id: 'zh-gram-bu-xia-qu',
    pattern: '不下去',
    explanation: 'This potential complement shows that something cannot continue or cannot be carried through anymore.',
    examples: [
      { target: '我吃不下去了。', translation: 'I cannot keep eating anymore.' },
      { target: '这个话题我接不下去。', translation: 'I cannot carry this topic on.' },
      { target: '这么多我拿不下去。', translation: 'I cannot carry this much.' },
    ],
    level: 3,
    locationId: 'xiaolongbao',
  },
];

export const SHANGHAI_XIAOLONGBAO: Location = {
  id: 'xiaolongbao',
  cityId: 'shanghai',
  name: { en: 'Xiaolongbao Shop', zh: '小笼包店' },
  domain: 'restaurant',
  order: 4,
  backgroundImageUrl: runtimeAssetUrl('city.shanghai.location.dumpling-shop.backdrop.default'),
  ambientDescription:
    'A busy Shanghai xiaolongbao shop with bamboo steamers stacked high. The auntie at the counter calls out orders while the kitchen fills the room with steam, vinegar, and pepper. Customers squeeze past the narrow aisle, and every table is full of dumpling baskets, tea cups, and fast conversation.',
  levels: [
    {
      level: 0,
      name: 'SCRIPT',
      description: 'Can I read the characters on the sign and menu?',
      objectives: LEVEL_0_OBJECTIVES,
      estimatedSessionMinutes: 15,
      assessmentCriteria: {
        minAccuracy: 0.8,
        minItemsCompleted: 12,
        requiredObjectives: ['zh-script-xiaolongbao-characters'],
      },
    },
    {
      level: 1,
      name: 'PRONUNCIATION',
      description: 'Can I hear and repeat the tones clearly?',
      objectives: LEVEL_1_OBJECTIVES,
      estimatedSessionMinutes: 18,
      assessmentCriteria: {
        minAccuracy: 0.75,
        minItemsCompleted: 4,
        requiredObjectives: ['zh-pron-tone-pairs'],
      },
    },
    {
      level: 2,
      name: 'VOCABULARY',
      description: 'Do I know what the shop words mean?',
      objectives: LEVEL_2_OBJECTIVES,
      estimatedSessionMinutes: 20,
      assessmentCriteria: {
        minAccuracy: 0.8,
        minItemsCompleted: 8,
        requiredObjectives: ['zh-vocab-xiaolongbao-core', 'zh-vocab-xiaolongbao-social'],
      },
    },
    {
      level: 3,
      name: 'GRAMMAR',
      description: 'Can I build useful sentences in the shop scene?',
      objectives: LEVEL_3_OBJECTIVES,
      estimatedSessionMinutes: 20,
      assessmentCriteria: {
        minAccuracy: 0.8,
        minItemsCompleted: 5,
        requiredObjectives: ['zh-gram-bu-hui-vs-bu-yuan-yi'],
      },
    },
  ],
  vocabularyTargets: VOCABULARY_TARGETS,
  grammarTargets: GRAMMAR_TARGETS,
};
