import type { GrammarTarget, LearningObjective, Location, VocabularyTarget } from '../../types/objectives';
import { runtimeAssetUrl } from '@/lib/runtime-assets';

const LEVEL_0_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-script-shanghai-negotiation-core',
    levelNumber: 0,
    category: 'script',
    title: 'Recognize the negotiation characters',
    description: 'Read the core hanzi behind 方, 案, 愿, 意, and 装 as they appear in the overheard lunch scene.',
    targetItems: ['方', '案', '愿', '意', '装'],
    targetCount: 5,
    assessmentThreshold: 0.8,
    prerequisites: [],
    tags: ['hanzi', 'script', 'shanghai', 'negotiation'],
  },
  {
    id: 'zh-script-shanghai-contrast-forms',
    levelNumber: 0,
    category: 'script',
    title: 'Read contrast and stance characters',
    description: 'Spot the simple forms that drive the scene contrast: 不, 一, and 样.',
    targetItems: ['不', '一', '样'],
    targetCount: 3,
    assessmentThreshold: 0.85,
    prerequisites: [],
    tags: ['hanzi', 'script', 'contrast', 'pattern'],
  },
  {
    id: 'zh-script-shanghai-food-signage',
    levelNumber: 0,
    category: 'script',
    title: 'Read the dumpling shop signage',
    description: 'Recognize the food-shop characters the player keeps seeing around 小笼包店.',
    targetItems: ['小', '笼', '包'],
    targetCount: 3,
    assessmentThreshold: 0.85,
    prerequisites: [],
    tags: ['hanzi', 'script', 'food', 'signage'],
  },
];

const LEVEL_1_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-pron-shanghai-fangan-yuanyi',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Hear the tone pairs in 方案 and 愿意',
    description: 'Practice the pitch movement in the key H1 terms 方案 and 愿意 without flattening them into English stress.',
    targetItems: ['方案', '愿意'],
    targetCount: 2,
    assessmentThreshold: 0.75,
    prerequisites: ['zh-script-shanghai-negotiation-core'],
    tags: ['pronunciation', 'tones', 'fangan', 'yuanyi'],
  },
  {
    id: 'zh-pron-shanghai-buyiyang-sandhi',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Handle tone sandhi in 不一样',
    description: 'Listen for how 不 shifts naturally inside 不一样 and keep the phrase sounding spoken instead of dictionary-stiff.',
    targetItems: ['不一样'],
    targetCount: 1,
    assessmentThreshold: 0.75,
    prerequisites: ['zh-script-shanghai-contrast-forms'],
    tags: ['pronunciation', 'tone-sandhi', 'contrast'],
  },
  {
    id: 'zh-pron-shanghai-zhuang-pao',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Separate 装 from 跑',
    description: 'Drill the zhuang / pao contrast so the player can hear and produce the H1 challenge line clearly.',
    targetItems: ['装', '跑'],
    targetCount: 2,
    assessmentThreshold: 0.75,
    prerequisites: ['zh-script-shanghai-negotiation-core'],
    tags: ['pronunciation', 'minimal-pair', 'initials', 'finals'],
  },
];

const LEVEL_2_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-vocab-shanghai-negotiation',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Understand the negotiation vocabulary',
    description: 'Track the core business and stance vocabulary driving the overheard lunch conversation.',
    targetItems: ['方案', '愿意', '装', '不一样'],
    targetCount: 4,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-pron-shanghai-fangan-yuanyi', 'zh-pron-shanghai-buyiyang-sandhi'],
    tags: ['vocabulary', 'negotiation', 'stance'],
  },
  {
    id: 'zh-vocab-shanghai-shop-language',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn the shop and family words',
    description: 'Recognize the food, kinship, and phone-response words that make the dumpling shop scene feel lived in.',
    targetItems: ['小笼包', '蟹壳黄', '阿姨', '接', '重要'],
    targetCount: 5,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-script-shanghai-food-signage'],
    tags: ['vocabulary', 'food', 'family', 'scene-context'],
  },
  {
    id: 'zh-vocab-shanghai-character-judgment',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Read the judgment words around character',
    description: 'Understand the sharper words used to judge someone’s stubbornness, competence, and willingness.',
    targetItems: ['犟', '本事'],
    targetCount: 2,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-vocab-shanghai-negotiation'],
    tags: ['vocabulary', 'personality', 'subtext'],
  },
];

const LEVEL_3_OBJECTIVES: LearningObjective[] = [
  {
    id: 'zh-gram-shanghai-buhui-buyuanyi',
    levelNumber: 3,
    category: 'grammar',
    title: 'Distinguish 不会 from 不愿意',
    description: 'Tell the difference between inability and unwillingness so the player can hear the emotional stakes in H1 accurately.',
    targetItems: ['不会', '不愿意'],
    targetCount: 2,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-vocab-shanghai-negotiation'],
    tags: ['grammar', 'modality', 'willingness'],
  },
  {
    id: 'zh-gram-shanghai-ni-register',
    levelNumber: 3,
    category: 'grammar',
    title: 'Read 你 as register, not just “you”',
    description: 'Notice when 你 sounds plain, pointed, or intimate depending on context and tone.',
    targetItems: ['你'],
    targetCount: 1,
    assessmentThreshold: 0.75,
    prerequisites: ['zh-vocab-shanghai-shop-language'],
    tags: ['grammar', 'register', 'pronouns'],
  },
  {
    id: 'zh-gram-shanghai-le-aspect',
    levelNumber: 3,
    category: 'grammar',
    title: 'Track 了 as completed action',
    description: 'Hear how 了 marks a completed look or finished action in clipped dialogue.',
    targetItems: ['看了', '响三次了'],
    targetCount: 2,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-vocab-shanghai-negotiation'],
    tags: ['grammar', 'aspect', 'completed-action'],
  },
  {
    id: 'zh-gram-shanghai-buxiaqu',
    levelNumber: 3,
    category: 'grammar',
    title: 'Understand the potential complement in 装不下去',
    description: 'Catch how 下去 changes the line from “pretend” into “keep pretending.”',
    targetItems: ['装不下去'],
    targetCount: 1,
    assessmentThreshold: 0.8,
    prerequisites: ['zh-pron-shanghai-zhuang-pao', 'zh-vocab-shanghai-negotiation'],
    tags: ['grammar', 'potential-complement', 'scene-line'],
  },
];

export const SHANGHAI_VOCABULARY_TARGETS: VocabularyTarget[] = [
  { word: '方', romanization: 'fang', translation: 'square; side; the 方 in 方案', category: 'hanzi', level: 0, sceneContext: 'first character in the key word 方案', visualCue: 'the first stroke cluster in a negotiation note' },
  { word: '案', romanization: 'an', translation: 'plan; proposal; case', category: 'hanzi', level: 0, sceneContext: 'second character in 方案', visualCue: 'typed proposal pages on the table' },
  { word: '不', romanization: 'bu', translation: 'not', category: 'hanzi', level: 0, sceneContext: 'used inside 不一样 and 不愿意', visualCue: 'Tong highlights the negation character in red' },
  { word: '一', romanization: 'yi', translation: 'one', category: 'hanzi', level: 0, sceneContext: 'middle character in 不一样', visualCue: 'a single horizontal line in the phrase fragment' },
  { word: '样', romanization: 'yang', translation: 'kind; type; way', category: 'hanzi', level: 0, sceneContext: 'final character in 不一样', visualCue: 'a subtitle fragment freezing on 样' },
  { word: '愿', romanization: 'yuan', translation: 'be willing to', category: 'hanzi', level: 0, sceneContext: 'first character in 愿意', visualCue: 'Tong isolates the top-heavy character during a whisper' },
  { word: '意', romanization: 'yi', translation: 'meaning; intent; willingness', category: 'hanzi', level: 0, sceneContext: 'second character in 愿意', visualCue: 'the final character in the willingness line' },
  { word: '装', romanization: 'zhuang', translation: 'pretend; put on', category: 'hanzi', level: 0, sceneContext: 'core verb in the pair-group challenge line', visualCue: 'the subtitle fragment on the word 装' },
  { word: '小', romanization: 'xiao', translation: 'small', category: 'hanzi', level: 0, sceneContext: 'first character in 小笼包店 signage', visualCue: 'the first character on the shop sign' },
  { word: '笼', romanization: 'long', translation: 'basket; steamer basket', category: 'hanzi', level: 0, sceneContext: 'middle character in 小笼包', visualCue: 'stacked bamboo steamers behind the counter' },
  { word: '包', romanization: 'bao', translation: 'bun; wrapped thing', category: 'hanzi', level: 0, sceneContext: 'final character in 小笼包', visualCue: 'steaming dumplings opened at the table' },
  { word: '方案', romanization: 'fang\'an', translation: 'proposal', category: 'negotiation', level: 2, sceneContext: 'Shoucheng opens the scene by asking whether the proposal was read', visualCue: 'paperwork sitting mostly untouched beside the steamers' },
  { word: '愿意', romanization: 'yuanyi', translation: 'willing to', category: 'stance', level: 2, sceneContext: 'the argument shifts from ability to willingness', visualCue: 'Tong freezes the line on 愿意 during the second whisper' },
  { word: '装', romanization: 'zhuang', translation: 'pretend; put on an act', category: 'stance', level: 2, sceneContext: 'used to challenge whether someone can keep performing a role', visualCue: 'a sharp subtitle fragment after the pair-group choice lands' },
  { word: '不一样', romanization: 'buyiyang', translation: 'different', category: 'stance', level: 2, sceneContext: 'the rehearsed pitch phrase every show uses about itself', visualCue: 'Shoucheng’s polished line contrasted with Dingman’s refusal' },
  { word: '小笼包', romanization: 'xiaolongbao', translation: 'soup dumpling', category: 'food', level: 2, sceneContext: 'the shop’s signature food and the player’s visual anchor', visualCue: 'bamboo steamer with delicate soup dumplings' },
  { word: '蟹壳黄', romanization: 'xiekehuang', translation: 'sesame pastry', category: 'food', level: 2, sceneContext: 'Dingman uses it as a food-first deflection', visualCue: 'flaky golden pastry next to a vinegar dish' },
  { word: '阿姨', romanization: 'ayi', translation: 'auntie; older woman', category: 'kinship', level: 2, sceneContext: 'the shop owner’s social role in the room', visualCue: 'Fang Ayi wiping the table with a practiced hand' },
  { word: '犟', romanization: 'jiang', translation: 'stubborn in a hard, proud way', category: 'personality', level: 2, sceneContext: 'part of Fang Ayi’s gated reveal about the Qu family', visualCue: 'a close-up of the auntie’s mouth tightening before the reveal' },
  { word: '本事', romanization: 'benshi', translation: 'ability; real capability', category: 'personality', level: 2, sceneContext: 'used to distinguish earned confidence from insecure stubbornness', visualCue: 'Tong breaks down the reveal after the credit spend' },
  { word: '接', romanization: 'jie', translation: 'to answer (a phone)', category: 'action', level: 2, sceneContext: 'Dingman tells him to answer the call', visualCue: 'a phone vibrating beside untouched cash' },
  { word: '重要', romanization: 'zhongyao', translation: 'important', category: 'judgment', level: 2, sceneContext: 'the phone call beat that exposes what matters', visualCue: 'the third ring cutting through the shop silence' },
];

export const SHANGHAI_GRAMMAR_TARGETS: GrammarTarget[] = [
  {
    id: 'zh-gram-shanghai-buhui-buyuanyi',
    pattern: '不会 vs 不愿意',
    explanation: '不会 means someone cannot do something; 不愿意 means they do not want to do it. H1 turns that difference into social tension.',
    examples: [
      { target: '他不会说假话。', translation: 'He cannot tell lies.' },
      { target: '他不愿意装。', translation: 'He is unwilling to pretend.' },
    ],
    level: 3,
    locationId: 'dumpling_shop',
  },
  {
    id: 'zh-gram-shanghai-ni-register',
    pattern: '你 as register',
    explanation: '你 is simple on paper, but in tight dialogue it can feel neutral, pointed, or intimate depending on tone and context.',
    examples: [
      { target: '你接吧。', translation: 'You should answer it.' },
      { target: '你说得对。', translation: 'You are right.' },
    ],
    level: 3,
    locationId: 'dumpling_shop',
  },
  {
    id: 'zh-gram-shanghai-le-aspect',
    pattern: '了 for completed action',
    explanation: '了 marks the action as completed or newly relevant, which keeps the lunch scene terse and immediate.',
    examples: [
      { target: '方案你看过了。', translation: 'You have already looked at the proposal.' },
      { target: '响三次了。', translation: 'It has rung three times already.' },
    ],
    level: 3,
    locationId: 'dumpling_shop',
  },
  {
    id: 'zh-gram-shanghai-buxiaqu',
    pattern: 'V 不下去',
    explanation: '不下去 shows someone cannot continue an action or maintain a state any longer.',
    examples: [
      { target: '我觉得你装不下去。', translation: 'I think you cannot keep pretending.' },
      { target: '这种话我听不下去。', translation: 'I cannot keep listening to this kind of talk.' },
    ],
    level: 3,
    locationId: 'dumpling_shop',
  },
];

export const SHANGHAI_XIAOLONGBAO: Location = {
  id: 'dumpling_shop',
  cityId: 'shanghai',
  name: { en: 'Xiaolongbao Shop', zh: '小笼包店' },
  domain: 'restaurant',
  order: 4,
  backgroundImageUrl: runtimeAssetUrl('city.shanghai.location.dumpling-shop.backdrop.default'),
  ambientDescription:
    'A small Shanghai xiaolongbao shop in the mid-afternoon lull. Warm fluorescent light, worn tile, stacked bamboo steamers, and a cool blue wash from the front glass create the feeling of a lived-in neighborhood room where business and gossip overlap.',
  levels: [
    {
      level: 0,
      name: 'SCRIPT',
      description: 'Can I recognize the hanzi that keep showing up in the scene?',
      objectives: LEVEL_0_OBJECTIVES,
      estimatedSessionMinutes: 12,
      assessmentCriteria: {
        minAccuracy: 0.8,
        minItemsCompleted: 9,
        requiredObjectives: ['zh-script-shanghai-negotiation-core'],
      },
    },
    {
      level: 1,
      name: 'PRONUNCIATION',
      description: 'Can I hear the tone shape and say the key lines cleanly?',
      objectives: LEVEL_1_OBJECTIVES,
      estimatedSessionMinutes: 14,
      assessmentCriteria: {
        minAccuracy: 0.75,
        minItemsCompleted: 5,
        requiredObjectives: ['zh-pron-shanghai-fangan-yuanyi'],
      },
    },
    {
      level: 2,
      name: 'VOCABULARY',
      description: 'Do I know the scene words well enough to follow the power shift?',
      objectives: LEVEL_2_OBJECTIVES,
      estimatedSessionMinutes: 18,
      assessmentCriteria: {
        minAccuracy: 0.8,
        minItemsCompleted: 11,
        requiredObjectives: ['zh-vocab-shanghai-negotiation'],
      },
    },
    {
      level: 3,
      name: 'GRAMMAR',
      description: 'Can I unpack the grammar that makes the subtext land?',
      objectives: LEVEL_3_OBJECTIVES,
      estimatedSessionMinutes: 18,
      assessmentCriteria: {
        minAccuracy: 0.8,
        minItemsCompleted: 6,
        requiredObjectives: ['zh-gram-shanghai-buhui-buyuanyi'],
      },
    },
  ],
  vocabularyTargets: SHANGHAI_VOCABULARY_TARGETS,
  grammarTargets: SHANGHAI_GRAMMAR_TARGETS,
};
