import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { resolveCaptionLanguage } from '../caption-language-resolver.ts';

const basePreferences = {
  languages: {
    fluentLanguages: ['en'],
    targetLanguages: ['ko'],
    primaryTarget: 'ko',
    translationLanguage: 'en',
  },
  subtitles: {
    overlayEnabled: true,
    showOriginal: true,
    showRomanization: true,
    showTranslation: true,
    romanizationSystem: 'romaji-hepburn',
    fontSize: 24,
    fontFamily: 'system-ui',
    textColor: '#fff',
    backgroundColor: 'rgba(0,0,0,0.75)',
    position: 'bottom',
    karaokeEnabled: true,
    karaokeHighlightColor: '#fbbf24',
  },
  shortcuts: {},
  theme: 'system',
  autoPauseOnNewWord: false,
  showDifficultyIndicators: true,
};

describe('resolveCaptionLanguage', () => {
  it('keeps a provisional track when metadata is non-CJK before cues are fetched', () => {
    const decision = resolveCaptionLanguage({
      preferences: basePreferences,
      tracks: [
        { id: 'en', label: 'English', language: 'en', isAutoGenerated: false, isDefault: true },
      ],
      selectedTrackId: null,
      manualTrackOverride: false,
      cues: [],
      pageMetadata: {},
    });

    assert.equal(decision.shouldShowOverlay, true);
    assert.equal(decision.selectedTrackId, 'en');
    assert.equal(decision.reasonCode, 'awaiting-cue-validation');
  });

  it('trusts cue text when the chosen track is mislabeled as non-CJK', () => {
    const decision = resolveCaptionLanguage({
      preferences: basePreferences,
      tracks: [
        { id: 'en', label: 'English', language: 'en', isAutoGenerated: false, isDefault: true },
      ],
      selectedTrackId: 'en',
      manualTrackOverride: false,
      cues: [
        { id: '1', startTime: 0, endTime: 500, text: '안녕하세요' },
      ],
      pageMetadata: {},
    });

    assert.equal(decision.shouldShowOverlay, true);
    assert.equal(decision.selectedTrackId, 'en');
    assert.equal(decision.sourceLanguage, 'ko');
    assert.equal(decision.reasonCode, 'cue-text-only');
  });
});
