import type { SubtitleCue, LanguageCode } from '@tong/core';

/**
 * Platform adapter interface
 * Each video platform needs its own adapter implementation
 */
export interface PlatformAdapter {
  /** Platform identifier */
  readonly platform: string;

  /** Wait for video element to be available */
  waitForVideo(): Promise<HTMLVideoElement | null>;

  /** Get current video ID */
  getVideoId(): string | null;

  /** Get video title */
  getVideoTitle(): string | null;

  /** Get available subtitle tracks */
  getSubtitleTracks(): Promise<SubtitleTrackInfo[]>;

  /** Get subtitles for a track */
  getSubtitles(trackId: string): Promise<SubtitleCue[]>;

  /** Get container element for overlay */
  getOverlayContainer(): HTMLElement | null;

  /** Subscribe to video time updates */
  onTimeUpdate(callback: (time: number) => void): () => void;

  /** Subscribe to playback rate changes */
  onPlaybackRateChange(callback: (rate: number) => void): () => void;

  /** Get current playback state */
  getPlaybackState(): PlaybackState;

  /** Subscribe to late-arriving captions (optional) */
  onCaptionsReceived?(callback: (lang: string, cues: SubtitleCue[]) => void): () => void;
}

/**
 * Information about an available subtitle track
 */
export interface SubtitleTrackInfo {
  /** Track identifier */
  id: string;
  /** Display label */
  label: string;
  /** Language code */
  language: LanguageCode;
  /** Whether this is auto-generated */
  isAutoGenerated: boolean;
  /** Whether this is the default track */
  isDefault: boolean;
}

/**
 * Current playback state
 */
export interface PlaybackState {
  /** Current time in milliseconds */
  currentTime: number;
  /** Playback rate (1.0 = normal) */
  playbackRate: number;
  /** Whether video is playing */
  isPlaying: boolean;
  /** Whether video is fullscreen */
  isFullscreen: boolean;
}
