import { render } from 'preact';
import { useState, useEffect } from 'preact/hooks';
import type { UserPreferences } from '@tong/core';

import './styles.css';

interface TrackInfo {
  id: string;
  label: string;
  language: string;
  isAutoGenerated: boolean;
  isDefault: boolean;
}

const LANG_LABELS: Record<string, string> = {
  ko: 'Korean',
  ja: 'Japanese',
  zh: 'Chinese',
  en: 'English',
};

function Popup() {
  const [preferences, setPreferences] = useState<UserPreferences | null>(null);
  const [loading, setLoading] = useState(true);
  const [subtitlesVisible, setSubtitlesVisible] = useState(true);
  const [hasOverlay, setHasOverlay] = useState(false);
  const [tracks, setTracks] = useState<TrackInfo[]>([]);
  const [selectedTrackId, setSelectedTrackId] = useState<string | null>(null);
  const [detectedLanguage, setDetectedLanguage] = useState<string | null>(null);

  useEffect(() => {
    loadPreferences();
    loadOverlayState();
  }, []);

  const loadPreferences = async () => {
    try {
      const response = await chrome.runtime.sendMessage({ type: 'GET_PREFERENCES' });
      if (response.success) {
        setPreferences(response.data);
      }
    } catch (error) {
      console.error('Error loading preferences:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadOverlayState = async () => {
    try {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab?.id) {
        const stateResp = await chrome.tabs.sendMessage(tab.id, { type: 'GET_OVERLAY_STATE' });
        if (stateResp?.success) {
          setSubtitlesVisible(stateResp.data.isVisible);
          setHasOverlay(stateResp.data.hasOverlay);
          setDetectedLanguage(stateResp.data.detectedLanguage || null);
        }

        const tracksResp = await chrome.tabs.sendMessage(tab.id, { type: 'GET_TRACKS' });
        if (tracksResp?.success) {
          setTracks(tracksResp.data.tracks || []);
          setSelectedTrackId(tracksResp.data.selectedTrackId || null);
          if (tracksResp.data.detectedLanguage) {
            setDetectedLanguage(tracksResp.data.detectedLanguage);
          }
        }
      }
    } catch {
      // Content script not injected on this page
    }
  };

  const toggleOverlay = async () => {
    try {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab?.id) {
        const response = await chrome.tabs.sendMessage(tab.id, { type: 'TOGGLE_OVERLAY' });
        if (response?.success) {
          setSubtitlesVisible(response.data.isVisible);
        }
      }
    } catch {
      // Content script not injected
    }
  };

  const toggleSetting = async (key: string) => {
    if (!preferences) return;

    const updates = {
      subtitles: {
        ...preferences.subtitles,
        [key]: !preferences.subtitles[key as keyof typeof preferences.subtitles],
      },
    };

    const response = await chrome.runtime.sendMessage({
      type: 'SET_PREFERENCES',
      payload: updates,
    });

    if (response.success) {
      setPreferences({ ...preferences, ...updates });

      // Notify content script
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab?.id) {
        await chrome.tabs.sendMessage(tab.id, { type: 'UPDATE_PREFERENCES' });
      }
    }
  };

  const changeLearningLanguage = async (lang: string) => {
    if (!preferences) return;

    const updates = {
      languages: {
        ...preferences.languages,
        primaryTarget: lang,
      },
    };

    const response = await chrome.runtime.sendMessage({
      type: 'SET_PREFERENCES',
      payload: updates,
    });

    if (response.success) {
      setPreferences({ ...preferences, ...updates });

      // Notify content script — will switch track if matching one available
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab?.id) {
        await chrome.tabs.sendMessage(tab.id, { type: 'UPDATE_PREFERENCES' });
        // Refresh track state after switch
        setTimeout(async () => {
          try {
            const resp = await chrome.tabs.sendMessage(tab.id!, { type: 'GET_TRACKS' });
            if (resp?.success) {
              setSelectedTrackId(resp.data.selectedTrackId || null);
              setDetectedLanguage(resp.data.detectedLanguage || null);
            }
          } catch { /* ignore */ }
        }, 500);
      }
    }
  };

  const changeTranslationLanguage = async (lang: string) => {
    if (!preferences) return;

    const updates = {
      languages: {
        ...preferences.languages,
        translationLanguage: lang,
      },
    };

    const response = await chrome.runtime.sendMessage({
      type: 'SET_PREFERENCES',
      payload: updates,
    });

    if (response.success) {
      setPreferences({ ...preferences, ...updates });

      // Notify content script to re-translate
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab?.id) {
        await chrome.tabs.sendMessage(tab.id, { type: 'UPDATE_PREFERENCES' });
      }
    }
  };

  const changeTrack = async (trackId: string) => {
    try {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab?.id) {
        const response = await chrome.tabs.sendMessage(tab.id, {
          type: 'CHANGE_TRACK',
          payload: { trackId },
        });
        if (response?.success) {
          setSelectedTrackId(trackId);
          setDetectedLanguage(response.data.detectedLanguage || null);
        }
      }
    } catch {
      // Content script not available
    }
  };

  const openOptions = () => {
    chrome.runtime.openOptionsPage();
  };

  if (loading) {
    return (
      <div className="popup">
        <div className="loading">Loading...</div>
      </div>
    );
  }

  return (
    <div className="popup">
      <header className="header">
        <h1>Tong</h1>
        <span className="version">v0.1.0</span>
      </header>

      <main className="content">
        <section className="quick-toggles">
          <button
            className={`toggle-btn primary${subtitlesVisible ? ' active' : ''}`}
            onClick={toggleOverlay}
            disabled={!hasOverlay}
            title={!hasOverlay ? 'Navigate to a video page first' : ''}
          >
            {!hasOverlay ? 'No Video Detected' : subtitlesVisible ? 'Hide Subtitles' : 'Show Subtitles'}
          </button>

          <div className="toggle-row">
            <label>
              <input
                type="checkbox"
                checked={preferences?.subtitles.showOriginal}
                onChange={() => toggleSetting('showOriginal')}
              />
              Original
            </label>

            <label>
              <input
                type="checkbox"
                checked={preferences?.subtitles.showRomanization}
                onChange={() => toggleSetting('showRomanization')}
              />
              Romanization
            </label>

            <label>
              <input
                type="checkbox"
                checked={preferences?.subtitles.showTranslation}
                onChange={() => toggleSetting('showTranslation')}
              />
              Translation
            </label>
          </div>

          <div className="toggle-row">
            <label>
              <input
                type="checkbox"
                checked={preferences?.subtitles.karaokeEnabled}
                onChange={() => toggleSetting('karaokeEnabled')}
              />
              Karaoke Mode
            </label>
          </div>
        </section>

        <section className="language-info">
          <div className="info-row">
            <span className="label">Learning:</span>
            <select
              className="lang-select"
              value={preferences?.languages.primaryTarget || 'ko'}
              onChange={(e) => changeLearningLanguage((e.target as HTMLSelectElement).value)}
            >
              <option value="ko">Korean</option>
              <option value="ja">Japanese</option>
              <option value="zh">Chinese (Simplified)</option>
              <option value="zh-TW">Chinese (Traditional)</option>
            </select>
          </div>
          <div className="info-row">
            <span className="label">Translate to:</span>
            <select
              className="lang-select"
              value={preferences?.languages.translationLanguage || 'en'}
              onChange={(e) => changeTranslationLanguage((e.target as HTMLSelectElement).value)}
            >
              {[
                { value: 'en', label: 'English' },
                { value: 'zh', label: 'Chinese (Simplified)' },
                { value: 'zh-TW', label: 'Chinese (Traditional)' },
                { value: 'ko', label: 'Korean' },
                { value: 'ja', label: 'Japanese' },
              ]
                .filter(opt => {
                  const primary = preferences?.languages.primaryTarget || '';
                  // Filter out exact match and zh/zh-TW overlap with learning language
                  if (opt.value === primary) return false;
                  if (opt.value === 'zh' && primary === 'zh-TW') return false;
                  if (opt.value === 'zh-TW' && primary === 'zh') return false;
                  return true;
                })
                .map(opt => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))
              }
            </select>
          </div>

          {tracks.length > 0 && (
            <div className="info-row">
              <span className="label">Subtitle track:</span>
              <select
                className="lang-select"
                value={selectedTrackId || ''}
                onChange={(e) => changeTrack((e.target as HTMLSelectElement).value)}
              >
                {tracks.map((t) => (
                  <option key={t.id} value={t.id}>
                    {t.label || LANG_LABELS[t.language] || t.language}
                    {t.isAutoGenerated ? ' (auto)' : ''}
                  </option>
                ))}
              </select>
            </div>
          )}

          {detectedLanguage && (
            <div className="info-row">
              <span className="label">Detected:</span>
              <span className="value">
                {LANG_LABELS[detectedLanguage] || detectedLanguage.toUpperCase()}
              </span>
            </div>
          )}
        </section>
      </main>

      <footer className="footer">
        <button className="settings-btn" onClick={openOptions}>
          Settings
        </button>
      </footer>
    </div>
  );
}

render(<Popup />, document.getElementById('app')!);
