ALTER TABLE signups ADD COLUMN proficiency_ko TEXT DEFAULT NULL;
ALTER TABLE signups ADD COLUMN proficiency_ja TEXT DEFAULT NULL;
ALTER TABLE signups ADD COLUMN proficiency_zh TEXT DEFAULT NULL;
ALTER TABLE signups ADD COLUMN explain_ko TEXT DEFAULT NULL;
ALTER TABLE signups ADD COLUMN explain_ja TEXT DEFAULT NULL;
ALTER TABLE signups ADD COLUMN explain_zh TEXT DEFAULT NULL;
ALTER TABLE signups ADD COLUMN has_preferences INTEGER DEFAULT 0;
ALTER TABLE signups ADD COLUMN preferences_at TEXT DEFAULT NULL;
