import type { SubtitleCue, UserPreferences } from '@tong/core';
import type { SubtitleTrackInfo } from './adapters/types';

export type ResolverReasonCode =
  | 'manual-track-selected'
  | 'track-metadata-matched-cues'
  | 'track-metadata-only'
  | 'cue-text-only'
  | 'metadata-heuristic'
  | 'learner-tiebreak'
  | 'insufficient-confidence'
  | 'overlay-disabled-by-user'
  | 'no-cjk-track-available';

export interface TrackSelectionContext {
  preferences: UserPreferences | null;
  tracks: SubtitleTrackInfo[];
  selectedTrackId: string | null;
  manualTrackOverride: boolean;
  cues: SubtitleCue[];
  pageMetadata?: {
    defaultAudioLanguage?: string | null;
    defaultLanguage?: string | null;
    title?: string | null;
    description?: string | null;
  };
}

export interface ResolverDecision {
  sourceLanguage: string | null;
  selectedTrackId: string | null;
  confidence: number;
  shouldShowOverlay: boolean;
  reasonCode: ResolverReasonCode;
  detail: string;
}

const CJK_CODES = ['ko', 'ja', 'zh', 'zh-Hans', 'zh-Hant', 'zh-CN', 'zh-TW'];

const normalizeLang = (value: string | null | undefined): string | null => {
  if (!value) return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
};

export const isCjkLanguage = (language: string | null | undefined): boolean => {
  const lang = normalizeLang(language);
  if (!lang) return false;
  return CJK_CODES.some((code) => lang === code || lang.startsWith(`${code}-`));
};

const detectCueTextLanguage = (cues: SubtitleCue[]): string | null => {
  if (cues.length === 0) return null;
  const sample = cues.slice(0, 24).map((c) => c.text).join('');
  if (!sample) return null;
  if (/[\uAC00-\uD7AF]/.test(sample)) return 'ko';
  if (/[\u3040-\u309F\u30A0-\u30FF]/.test(sample)) return 'ja';
  if (/[\u4E00-\u9FFF]/.test(sample)) return 'zh';
  return null;
};

const resolveMetadataHeuristic = (metadata?: TrackSelectionContext['pageMetadata']): string | null => {
  const candidates = [metadata?.defaultAudioLanguage, metadata?.defaultLanguage];
  for (const candidate of candidates) {
    if (isCjkLanguage(candidate)) return normalizeLang(candidate);
  }
  return null;
};

const pickTrack = (tracks: SubtitleTrackInfo[], preferredLanguage: string | null): SubtitleTrackInfo | null => {
  if (preferredLanguage) {
    const exact = tracks.find((t) => t.language === preferredLanguage && !t.isAutoGenerated);
    if (exact) return exact;
    const prefix = tracks.find((t) => t.language.startsWith(`${preferredLanguage}-`) && !t.isAutoGenerated);
    if (prefix) return prefix;
    const exactAuto = tracks.find((t) => t.language === preferredLanguage);
    if (exactAuto) return exactAuto;
    const prefixAuto = tracks.find((t) => t.language.startsWith(`${preferredLanguage}-`));
    if (prefixAuto) return prefixAuto;
  }

  return (
    tracks.find((t) => isCjkLanguage(t.language) && t.isDefault && !t.isAutoGenerated) ||
    tracks.find((t) => isCjkLanguage(t.language) && !t.isAutoGenerated) ||
    tracks.find((t) => isCjkLanguage(t.language) && t.isDefault) ||
    tracks.find((t) => isCjkLanguage(t.language)) ||
    null
  );
};

export const resolveCaptionLanguage = (ctx: TrackSelectionContext): ResolverDecision => {
  const overlayEnabled = ctx.preferences?.subtitles?.overlayEnabled ?? true;
  if (!overlayEnabled) {
    return {
      sourceLanguage: null,
      selectedTrackId: null,
      confidence: 1,
      shouldShowOverlay: false,
      reasonCode: 'overlay-disabled-by-user',
      detail: 'Overlay is disabled in saved preferences.',
    };
  }

  const cjkTracks = ctx.tracks.filter((track) => isCjkLanguage(track.language));
  if (cjkTracks.length === 0) {
    return {
      sourceLanguage: null,
      selectedTrackId: null,
      confidence: 0,
      shouldShowOverlay: false,
      reasonCode: 'no-cjk-track-available',
      detail: 'No CJK caption tracks were available for this video.',
    };
  }

  const cueLanguage = detectCueTextLanguage(ctx.cues);

  if (ctx.manualTrackOverride && ctx.selectedTrackId) {
    const manualTrack = cjkTracks.find((track) => track.id === ctx.selectedTrackId) ?? null;
    const sourceLanguage = normalizeLang(manualTrack?.language) ?? cueLanguage;
    const mismatch = Boolean(sourceLanguage && cueLanguage && !sourceLanguage.startsWith(cueLanguage));
    return {
      sourceLanguage,
      selectedTrackId: manualTrack?.id ?? ctx.selectedTrackId,
      confidence: mismatch ? 0.55 : 0.96,
      shouldShowOverlay: !mismatch,
      reasonCode: 'manual-track-selected',
      detail: mismatch
        ? 'Manual track language conflicted with fetched cue text.'
        : 'Using user-selected subtitle track override.',
    };
  }

  const metadataHint = resolveMetadataHeuristic(ctx.pageMetadata);
  const trackByMetadata = pickTrack(cjkTracks, metadataHint);
  const resolvedTrack = trackByMetadata ?? pickTrack(cjkTracks, cueLanguage);
  const sourceLanguage = normalizeLang(resolvedTrack?.language) ?? cueLanguage;

  if (!sourceLanguage) {
    return {
      sourceLanguage: null,
      selectedTrackId: resolvedTrack?.id ?? null,
      confidence: 0.2,
      shouldShowOverlay: false,
      reasonCode: 'insufficient-confidence',
      detail: 'Could not confidently infer source language from tracks, cues, or metadata.',
    };
  }

  const mismatch = Boolean(cueLanguage && !sourceLanguage.startsWith(cueLanguage));
  if (mismatch) {
    return {
      sourceLanguage,
      selectedTrackId: resolvedTrack?.id ?? null,
      confidence: 0.45,
      shouldShowOverlay: false,
      reasonCode: 'insufficient-confidence',
      detail: `Track language ${sourceLanguage} disagreed with cue text ${cueLanguage}.`,
    };
  }

  if (cueLanguage && resolvedTrack?.language) {
    return {
      sourceLanguage,
      selectedTrackId: resolvedTrack.id,
      confidence: 0.9,
      shouldShowOverlay: true,
      reasonCode: 'track-metadata-matched-cues',
      detail: `Resolved from track metadata (${resolvedTrack.language}) and cue language (${cueLanguage}).`,
    };
  }

  if (resolvedTrack?.language) {
    return {
      sourceLanguage,
      selectedTrackId: resolvedTrack.id,
      confidence: 0.72,
      shouldShowOverlay: true,
      reasonCode: metadataHint ? 'metadata-heuristic' : 'track-metadata-only',
      detail: metadataHint
        ? `Resolved from video metadata (${metadataHint}) and track metadata.`
        : 'Resolved from available track metadata.',
    };
  }

  return {
    sourceLanguage,
    selectedTrackId: null,
    confidence: 0.7,
    shouldShowOverlay: true,
    reasonCode: 'cue-text-only',
    detail: 'Resolved from cue text language with no matching track metadata.',
  };
};
