import type { SubtitleCue, UserPreferences } from '@tong/core';
import type { SubtitleTrackInfo } from './adapters/types';

export type ResolverReasonCode =
  | 'manual-track-selected'
  | 'track-metadata-matched-cues'
  | 'track-metadata-only'
  | 'cue-text-only'
  | 'metadata-heuristic'
  | 'awaiting-cue-validation'
  | 'learner-tiebreak'
  | 'insufficient-confidence'
  | 'overlay-disabled-by-user'
  | 'no-cjk-track-available';

export interface TrackSelectionContext {
  preferences: UserPreferences | null;
  tracks: SubtitleTrackInfo[];
  selectedTrackId: string | null;
  manualTrackOverride: boolean;
  cues: SubtitleCue[];
  pageMetadata?: {
    defaultAudioLanguage?: string | null;
    defaultLanguage?: string | null;
    title?: string | null;
    description?: string | null;
  };
}

export interface ResolverDecision {
  sourceLanguage: string | null;
  selectedTrackId: string | null;
  confidence: number;
  shouldShowOverlay: boolean;
  reasonCode: ResolverReasonCode;
  detail: string;
}

const CJK_CODES = ['ko', 'ja', 'zh', 'zh-Hans', 'zh-Hant', 'zh-CN', 'zh-TW'];

const normalizeLang = (value: string | null | undefined): string | null => {
  if (!value) return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
};

export const isCjkLanguage = (language: string | null | undefined): boolean => {
  const lang = normalizeLang(language);
  if (!lang) return false;
  return CJK_CODES.some((code) => lang === code || lang.startsWith(`${code}-`));
};

const detectCueTextLanguage = (cues: SubtitleCue[]): string | null => {
  if (cues.length === 0) return null;
  const sample = cues.slice(0, 24).map((c) => c.text).join('');
  if (!sample) return null;
  if (/[\uAC00-\uD7AF]/.test(sample)) return 'ko';
  if (/[\u3040-\u309F\u30A0-\u30FF]/.test(sample)) return 'ja';
  if (/[\u4E00-\u9FFF]/.test(sample)) return 'zh';
  return null;
};

const resolveMetadataHeuristic = (metadata?: TrackSelectionContext['pageMetadata']): string | null => {
  const candidates = [metadata?.defaultAudioLanguage, metadata?.defaultLanguage];
  for (const candidate of candidates) {
    if (isCjkLanguage(candidate)) return normalizeLang(candidate);
  }
  return null;
};

const pickTrack = (tracks: SubtitleTrackInfo[], preferredLanguage: string | null): SubtitleTrackInfo | null => {
  if (preferredLanguage) {
    const exact = tracks.find((t) => t.language === preferredLanguage && !t.isAutoGenerated);
    if (exact) return exact;
    const prefix = tracks.find((t) => t.language.startsWith(`${preferredLanguage}-`) && !t.isAutoGenerated);
    if (prefix) return prefix;
    const exactAuto = tracks.find((t) => t.language === preferredLanguage);
    if (exactAuto) return exactAuto;
    const prefixAuto = tracks.find((t) => t.language.startsWith(`${preferredLanguage}-`));
    if (prefixAuto) return prefixAuto;
  }

  return (
    tracks.find((t) => isCjkLanguage(t.language) && t.isDefault && !t.isAutoGenerated) ||
    tracks.find((t) => isCjkLanguage(t.language) && !t.isAutoGenerated) ||
    tracks.find((t) => isCjkLanguage(t.language) && t.isDefault) ||
    tracks.find((t) => isCjkLanguage(t.language)) ||
    null
  );
};

const pickCarrierTrack = (
  tracks: SubtitleTrackInfo[],
  selectedTrackId: string | null,
  preferredLanguage: string | null,
): SubtitleTrackInfo | null => {
  if (selectedTrackId) {
    const selected = tracks.find((track) => track.id === selectedTrackId);
    if (selected) return selected;
  }

  if (preferredLanguage) {
    const exact = tracks.find((track) => track.language === preferredLanguage && !track.isAutoGenerated);
    if (exact) return exact;
    const prefix = tracks.find((track) => track.language.startsWith(`${preferredLanguage}-`) && !track.isAutoGenerated);
    if (prefix) return prefix;
    const anyExact = tracks.find((track) => track.language === preferredLanguage);
    if (anyExact) return anyExact;
    const anyPrefix = tracks.find((track) => track.language.startsWith(`${preferredLanguage}-`));
    if (anyPrefix) return anyPrefix;
  }

  return (
    tracks.find((track) => track.isDefault && !track.isAutoGenerated) ||
    tracks.find((track) => track.isDefault) ||
    tracks.find((track) => !track.isAutoGenerated) ||
    tracks[0] ||
    null
  );
};

export const resolveCaptionLanguage = (ctx: TrackSelectionContext): ResolverDecision => {
  const overlayEnabled = ctx.preferences?.subtitles?.overlayEnabled ?? true;
  if (!overlayEnabled) {
    return {
      sourceLanguage: null,
      selectedTrackId: null,
      confidence: 1,
      shouldShowOverlay: false,
      reasonCode: 'overlay-disabled-by-user',
      detail: 'Overlay is disabled in saved preferences.',
    };
  }

  const cueLanguage = detectCueTextLanguage(ctx.cues);
  const metadataHint = resolveMetadataHeuristic(ctx.pageMetadata);
  const cjkTracks = ctx.tracks.filter((track) => isCjkLanguage(track.language));

  if (ctx.manualTrackOverride && ctx.selectedTrackId) {
    const manualTrack = ctx.tracks.find((track) => track.id === ctx.selectedTrackId) ?? null;
    const manualTrackLanguage = normalizeLang(manualTrack?.language);
    const sourceLanguage =
      (isCjkLanguage(manualTrackLanguage) ? manualTrackLanguage : null) ||
      cueLanguage;
    const mismatch = Boolean(
      cueLanguage &&
      manualTrackLanguage &&
      isCjkLanguage(manualTrackLanguage) &&
      !manualTrackLanguage.startsWith(cueLanguage)
    );

    if (!sourceLanguage) {
      return {
        sourceLanguage: null,
        selectedTrackId: manualTrack?.id ?? ctx.selectedTrackId,
        confidence: 0.25,
        shouldShowOverlay: false,
        reasonCode: 'insufficient-confidence',
        detail: 'Manual track selection did not provide reliable CJK metadata or cue text.',
      };
    }

    return {
      sourceLanguage,
      selectedTrackId: manualTrack?.id ?? ctx.selectedTrackId,
      confidence: mismatch ? 0.55 : cueLanguage ? 0.94 : 0.8,
      shouldShowOverlay: !mismatch,
      reasonCode: 'manual-track-selected',
      detail: mismatch
        ? 'Manual track language conflicted with fetched cue text.'
        : 'Using user-selected subtitle track override.',
    };
  }

  if (cjkTracks.length === 0 && !cueLanguage && !isCjkLanguage(metadataHint)) {
    const provisionalTrack = pickCarrierTrack(ctx.tracks, ctx.selectedTrackId, null);
    if (provisionalTrack) {
      return {
        sourceLanguage: null,
        selectedTrackId: provisionalTrack.id,
        confidence: 0.35,
        shouldShowOverlay: true,
        reasonCode: 'awaiting-cue-validation',
        detail: 'Fetching captions to verify source language because track metadata is non-CJK.',
      };
    }

    return {
      sourceLanguage: null,
      selectedTrackId: null,
      confidence: 0,
      shouldShowOverlay: false,
      reasonCode: 'no-cjk-track-available',
      detail: 'No CJK caption tracks were available for this video.',
    };
  }

  const trackByMetadata = pickTrack(cjkTracks, metadataHint);
  const resolvedTrack =
    trackByMetadata ??
    pickTrack(cjkTracks, cueLanguage) ??
    pickCarrierTrack(ctx.tracks, ctx.selectedTrackId, metadataHint) ??
    pickCarrierTrack(ctx.tracks, ctx.selectedTrackId, cueLanguage);
  const resolvedTrackLanguage = normalizeLang(resolvedTrack?.language);
  const sourceLanguage =
    (isCjkLanguage(resolvedTrackLanguage) ? resolvedTrackLanguage : null) ||
    cueLanguage ||
    metadataHint;

  if (!sourceLanguage) {
    return {
      sourceLanguage: null,
      selectedTrackId: resolvedTrack?.id ?? null,
      confidence: 0.2,
      shouldShowOverlay: false,
      reasonCode: 'insufficient-confidence',
      detail: 'Could not confidently infer source language from tracks, cues, or metadata.',
    };
  }

  const mismatch = Boolean(
    cueLanguage &&
    resolvedTrackLanguage &&
    isCjkLanguage(resolvedTrackLanguage) &&
    !resolvedTrackLanguage.startsWith(cueLanguage)
  );
  if (mismatch) {
    return {
      sourceLanguage,
      selectedTrackId: resolvedTrack?.id ?? null,
      confidence: 0.45,
      shouldShowOverlay: false,
      reasonCode: 'insufficient-confidence',
      detail: `Track language ${resolvedTrackLanguage} disagreed with cue text ${cueLanguage}.`,
    };
  }

  if (cueLanguage && resolvedTrack?.language) {
    return {
      sourceLanguage,
      selectedTrackId: resolvedTrack.id,
      confidence: 0.9,
      shouldShowOverlay: true,
      reasonCode: isCjkLanguage(resolvedTrack.language) ? 'track-metadata-matched-cues' : 'cue-text-only',
      detail: isCjkLanguage(resolvedTrack.language)
        ? `Resolved from track metadata (${resolvedTrack.language}) and cue language (${cueLanguage}).`
        : 'Resolved from cue text language while track metadata remained non-CJK.',
    };
  }

  if (resolvedTrackLanguage && isCjkLanguage(resolvedTrackLanguage)) {
    return {
      sourceLanguage,
      selectedTrackId: resolvedTrack?.id ?? null,
      confidence: 0.72,
      shouldShowOverlay: true,
      reasonCode: metadataHint ? 'metadata-heuristic' : 'track-metadata-only',
      detail: metadataHint
        ? `Resolved from video metadata (${metadataHint}) and track metadata.`
        : 'Resolved from available track metadata.',
    };
  }

  return {
    sourceLanguage,
    selectedTrackId: resolvedTrack?.id ?? null,
    confidence: cueLanguage ? 0.7 : 0.55,
    shouldShowOverlay: true,
    reasonCode: cueLanguage ? 'cue-text-only' : 'metadata-heuristic',
    detail: cueLanguage
      ? 'Resolved from cue text language with no matching CJK track metadata.'
      : 'Resolved from video metadata with no matching CJK track metadata.',
  };
};
