import type { LanguageCode, SubtitleCue } from './subtitle';
import type { RomanizationResult, RomanizationOptions } from './romanization';
import type { VocabularyItem, ReviewResult } from './vocabulary';

/**
 * Standard API response wrapper
 */
export interface ApiResponse<T> {
  /** Response data */
  data: T;
  /** Success indicator */
  success: boolean;
  /** Error message if any */
  error?: string;
  /** Request timestamp */
  timestamp: number;
}

/**
 * Paginated response
 */
export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  /** Pagination info */
  pagination: {
    page: number;
    pageSize: number;
    totalItems: number;
    totalPages: number;
    hasMore: boolean;
  };
}

// Translation API

export interface TranslateRequest {
  /** Text to translate */
  text: string;
  /** Source language (auto-detect if not specified) */
  sourceLang?: LanguageCode;
  /** Target language */
  targetLang: LanguageCode;
}

export interface TranslateResponse {
  /** Original text */
  original: string;
  /** Translated text */
  translated: string;
  /** Detected/specified source language */
  sourceLang: LanguageCode;
  /** Target language */
  targetLang: LanguageCode;
  /** Whether result was from cache */
  cached: boolean;
}

export interface BatchTranslateRequest {
  /** Texts to translate */
  texts: string[];
  /** Source language */
  sourceLang?: LanguageCode;
  /** Target language */
  targetLang: LanguageCode;
}

export interface BatchTranslateResponse {
  /** Translations in same order as input */
  translations: TranslateResponse[];
  /** Total processing time (ms) */
  processingTime: number;
  /** Cache hit rate */
  cacheHitRate: number;
}

// Romanization API

export interface RomanizeRequest {
  /** Text to romanize */
  text: string;
  /** Source language */
  language: 'zh' | 'ja' | 'ko';
  /** Options */
  options?: RomanizationOptions;
}

export type RomanizeResponse = RomanizationResult;

// Subtitles API

export interface GetSubtitlesRequest {
  /** Video ID */
  videoId: string;
  /** Platform */
  platform: 'youtube' | 'bilibili' | 'viki';
  /** Languages to fetch */
  languages?: LanguageCode[];
}

export interface GetSubtitlesResponse {
  /** Video ID */
  videoId: string;
  /** Available subtitle tracks */
  tracks: {
    language: LanguageCode;
    label: string;
    isAutoGenerated: boolean;
  }[];
}

export interface ProcessSubtitlesRequest {
  /** Video ID */
  videoId: string;
  /** Platform */
  platform: string;
  /** Original subtitle cues */
  cues: SubtitleCue[];
  /** Source language */
  sourceLang: LanguageCode;
  /** Target translation language */
  targetLang: LanguageCode;
  /** Include romanization */
  includeRomanization: boolean;
  /** Include word-level timing */
  includeWordTiming: boolean;
}

export interface ProcessSubtitlesResponse {
  /** Processed cues with translations and romanization */
  cues: SubtitleCue[];
  /** Processing stats */
  stats: {
    totalCues: number;
    translatedCues: number;
    romanizedCues: number;
    processingTimeMs: number;
  };
}

// Vocabulary API

export interface SaveVocabularyRequest {
  /** Word to save */
  word: string;
  /** Source language */
  language: LanguageCode;
  /** Translation */
  translation: string;
  /** Translation language */
  translationLanguage: LanguageCode;
  /** Video context */
  context?: {
    videoId: string;
    platform: string;
    videoTitle: string;
    timestamp: number;
    sentence: string;
  };
  /** Tags */
  tags?: string[];
}

export interface SaveVocabularyResponse {
  /** Created/updated vocabulary item */
  item: VocabularyItem;
  /** Whether item already existed */
  isNew: boolean;
}

export interface GetVocabularyRequest {
  /** Filter by language */
  language?: LanguageCode;
  /** Filter by tags */
  tags?: string[];
  /** Search query */
  search?: string;
  /** Page number */
  page?: number;
  /** Items per page */
  pageSize?: number;
}

// Review API

export interface GetReviewItemsRequest {
  /** Number of items to fetch */
  limit?: number;
  /** Filter by language */
  language?: LanguageCode;
}

export interface GetReviewItemsResponse {
  /** Items due for review */
  items: VocabularyItem[];
  /** Total items due */
  totalDue: number;
}

export interface SubmitReviewRequest {
  /** Review result */
  result: ReviewResult;
}

export interface SubmitReviewResponse {
  /** Updated review data */
  nextReviewDate: number;
  /** Updated interval */
  interval: number;
  /** Updated ease factor */
  easeFactor: number;
}
