/**
 * A single word with timing information for karaoke-style display
 */
export interface WordTiming {
  /** The word or character(s) */
  word: string;
  /** Start time in milliseconds */
  startTime: number;
  /** End time in milliseconds */
  endTime: number;
  /** Romanization (pinyin, romaji, etc.) */
  romanization?: string;
  /** Translation of this word */
  translation?: string;
}

/**
 * A subtitle cue (single subtitle entry)
 */
export interface SubtitleCue {
  /** Unique identifier */
  id: string;
  /** Start time in milliseconds */
  startTime: number;
  /** End time in milliseconds */
  endTime: number;
  /** Original text content */
  text: string;
  /** Word-level timing for karaoke display */
  words?: WordTiming[];
  /** Full romanization of the text */
  romanization?: string;
  /** Full translation of the text */
  translation?: string;
  /** Detected language of this cue */
  language?: LanguageCode;
}

/**
 * Supported subtitle formats
 */
export type SubtitleFormat = 'vtt' | 'srt' | 'ass' | 'ssa' | 'json';

/**
 * A complete subtitle track
 */
export interface SubtitleTrack {
  /** Track identifier (e.g., language code) */
  id: string;
  /** Display label for the track */
  label: string;
  /** Language of the subtitles */
  language: LanguageCode;
  /** Format of the source file */
  sourceFormat: SubtitleFormat;
  /** All subtitle cues */
  cues: SubtitleCue[];
  /** Whether this track has word-level timing */
  hasWordTiming: boolean;
}

/**
 * Supported language codes (ISO 639-1)
 */
export type LanguageCode =
  | 'zh' // Chinese
  | 'ja' // Japanese
  | 'ko' // Korean
  | 'en' // English
  | 'zh-TW' // Traditional Chinese
  | 'zh-CN' // Simplified Chinese
  | string; // Allow other language codes

/**
 * Processed subtitle with all enhancements applied
 */
export interface ProcessedSubtitle {
  /** Original subtitle track */
  original: SubtitleTrack;
  /** Romanized version */
  romanized?: SubtitleTrack;
  /** Translated version */
  translated?: SubtitleTrack;
  /** Video ID this subtitle belongs to */
  videoId: string;
  /** Platform (youtube, bilibili, etc.) */
  platform: string;
  /** Processing timestamp */
  processedAt: number;
  /** Source of the subtitles */
  source?: SubtitleSource;
}

/**
 * Subtitle source types - used for fallback strategy
 * Priority order: creator > auto > whisper > external > user
 */
export type SubtitleSourceType =
  | 'creator' // Creator-uploaded captions (highest quality)
  | 'auto' // Platform auto-generated (YouTube auto-captions)
  | 'whisper' // AI transcription (OpenAI Whisper API)
  | 'external' // External database (OpenSubtitles, subscene)
  | 'user'; // User-uploaded file

/**
 * Subtitle source metadata
 */
export interface SubtitleSource {
  /** Type of subtitle source */
  type: SubtitleSourceType;
  /** Quality indicator (0-100) */
  quality: SubtitleQuality;
  /** Whether this is the original creator's caption */
  isCreatorCaption: boolean;
  /** Whether this was auto-generated */
  isAutoGenerated: boolean;
  /** External source details if applicable */
  externalSource?: {
    provider: string;
    id: string;
    url?: string;
  };
  /** Transcription details if applicable */
  transcription?: {
    model: string; // e.g., 'whisper-1'
    confidence: number;
  };
}

/**
 * Quality levels for subtitles
 */
export type SubtitleQuality = 'high' | 'medium' | 'low' | 'unknown';

/**
 * Subtitle availability status for a video
 */
export interface SubtitleAvailability {
  /** Video ID */
  videoId: string;
  /** Platform */
  platform: string;
  /** Available subtitle tracks */
  available: SubtitleTrackInfo[];
  /** Best track for target language learning */
  recommended?: SubtitleTrackInfo;
  /** Whether transcription is needed (no suitable subtitles found) */
  needsTranscription: boolean;
}

/**
 * Basic info about an available subtitle track
 */
export interface SubtitleTrackInfo {
  /** Track language */
  language: LanguageCode;
  /** Display label */
  label: string;
  /** Source type */
  sourceType: SubtitleSourceType;
  /** Quality indicator */
  quality: SubtitleQuality;
  /** Is auto-generated */
  isAutoGenerated: boolean;
}

/**
 * Fallback strategy configuration
 */
export interface SubtitleFallbackConfig {
  /** Enable auto-captions as fallback */
  allowAutoCaption: boolean;
  /** Enable AI transcription (costs $) */
  allowWhisperTranscription: boolean;
  /** Enable external subtitle databases */
  allowExternalSources: boolean;
  /** Minimum quality threshold */
  minQuality: SubtitleQuality;
  /** Preferred languages in order */
  preferredLanguages: LanguageCode[];
}
