import type { Location, VocabularyTarget, GrammarTarget, LearningObjective } from '../types/objectives';

const LEVEL_0_OBJECTIVES: LearningObjective[] = [
  {
    id: 'ko-script-consonants-basic',
    levelNumber: 0,
    category: 'script',
    title: 'Learn 14 basic consonants',
    description: 'Recognize and name the 14 basic Korean consonants',
    targetItems: ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'],
    targetCount: 14,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-script-vowels-basic',
    levelNumber: 0,
    category: 'script',
    title: 'Learn 10 basic vowels',
    description: 'Recognize and name the 10 basic Korean vowels',
    targetItems: ['ㅏ', 'ㅑ', 'ㅓ', 'ㅕ', 'ㅗ', 'ㅛ', 'ㅜ', 'ㅠ', 'ㅡ', 'ㅣ'],
    targetCount: 10,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-script-blocks-2part',
    levelNumber: 0,
    category: 'script',
    title: 'Read 2-part syllable blocks',
    description: 'Combine consonant + vowel to read basic blocks like 가, 나, 다',
    targetItems: ['가', '나', '다', '라', '마', '바', '사', '아', '자', '카', '타', '파', '하'],
    targetCount: 13,
    assessmentThreshold: 0.7,
  },
  {
    id: 'ko-script-menu-reading',
    levelNumber: 0,
    category: 'script',
    title: 'Read menu items',
    description: 'Read food names from the stall menu',
    targetItems: ['오뎅', '떡볶이', '라면', '순대'],
    targetCount: 4,
    assessmentThreshold: 0.75,
  },
];

const LEVEL_1_OBJECTIVES: LearningObjective[] = [
  {
    id: 'ko-pron-jamo-all',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Pronounce all jamo correctly',
    description: 'Accurate pronunciation of all consonants and vowels',
    targetItems: ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ', 'ㅏ', 'ㅑ', 'ㅓ', 'ㅕ', 'ㅗ', 'ㅛ', 'ㅜ', 'ㅠ', 'ㅡ', 'ㅣ'],
    targetCount: 24,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-pron-batchim',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Learn 받침 (batchim) rules',
    description: 'Understand and apply final consonant pronunciation rules',
    targetItems: ['ㄱ받침', 'ㄴ받침', 'ㄹ받침', 'ㅁ받침', 'ㅂ받침', 'ㅇ받침', 'ㄷ받침'],
    targetCount: 7,
    assessmentThreshold: 0.7,
  },
  {
    id: 'ko-pron-food-words',
    levelNumber: 1,
    category: 'pronunciation',
    title: 'Pronounce 20 food words',
    description: 'Correctly pronounce common Korean food words from the stall',
    targetItems: ['떡볶이', '라면', '오뎅', '순대', '김밥', '어묵', '만두', '튀김', '꼬치', '호떡', '붕어빵', '떡꼬치', '소떡소떡', '핫도그', '군고구마', '비빔밥', '볶음밥', '잡채', '김치', '콜라'],
    targetCount: 20,
    assessmentThreshold: 0.75,
  },
];

const LEVEL_2_OBJECTIVES: LearningObjective[] = [
  {
    id: 'ko-vocab-food-items',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn 20 food items',
    description: 'Know the meaning and reading of 20 street food items',
    targetItems: ['떡볶이', '라면', '오뎅', '순대', '김밥', '어묵', '만두', '튀김', '꼬치', '호떡', '붕어빵', '비빔밥', '볶음밥', '김치', '콜라', '물', '주스', '소주', '맥주', '사이다'],
    targetCount: 20,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-vocab-taste-words',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn taste and texture words',
    description: 'Describe flavors: spicy, sweet, salty, delicious, etc.',
    targetItems: ['맵다', '달다', '짜다', '맛있다', '맛없다', '시다', '쓰다', '뜨겁다', '차갑다', '맵지 않다'],
    targetCount: 10,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-vocab-numbers',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn numbers for ordering',
    description: 'Count 1-5 with native Korean numbers for ordering',
    targetItems: ['하나', '둘', '셋', '넷', '다섯'],
    targetCount: 5,
    assessmentThreshold: 0.9,
  },
  {
    id: 'ko-vocab-basic-verbs',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn basic food verbs',
    description: 'Key verbs for ordering and eating',
    targetItems: ['먹다', '주다', '마시다', '사다', '시키다'],
    targetCount: 5,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-vocab-courtesy',
    levelNumber: 2,
    category: 'vocabulary',
    title: 'Learn courtesy phrases',
    description: 'Essential polite phrases for ordering',
    targetItems: ['주세요', '감사합니다', '잠시만요', '여기요', '얼마예요'],
    targetCount: 5,
    assessmentThreshold: 0.9,
  },
];

const LEVEL_3_OBJECTIVES: LearningObjective[] = [
  {
    id: 'ko-gram-juseyo',
    levelNumber: 3,
    category: 'grammar',
    title: 'Master N + 주세요 pattern',
    description: 'Use "noun + please" to order food politely',
    targetItems: ['N+주세요'],
    targetCount: 1,
    assessmentThreshold: 0.85,
  },
  {
    id: 'ko-gram-object-particle',
    levelNumber: 3,
    category: 'grammar',
    title: 'Learn 을/를 object particle',
    description: 'Use the object marker correctly with food nouns',
    targetItems: ['을/를'],
    targetCount: 1,
    assessmentThreshold: 0.8,
  },
  {
    id: 'ko-gram-counters',
    levelNumber: 3,
    category: 'grammar',
    title: 'Use number + counter patterns',
    description: 'Order using 하나, 두 개 etc. with counters',
    targetItems: ['N+개', '하나/둘/셋+개'],
    targetCount: 2,
    assessmentThreshold: 0.8,
  },
];

export const VOCABULARY_TARGETS: VocabularyTarget[] = [
  // Level 0 - script reading
  { word: '오뎅', romanization: 'odeng', translation: 'fish cake', category: 'food_item', level: 0, sceneContext: 'written on the menu board in big letters', visualCue: 'bubbling pot of fish cake skewers on the counter' },
  { word: '떡볶이', romanization: 'tteokbokki', translation: 'spicy rice cakes', category: 'food_item', level: 0, sceneContext: 'top item on the handwritten menu', visualCue: 'bright red sauce with cylindrical rice cakes in a flat pan' },
  { word: '라면', romanization: 'ramyeon', translation: 'instant noodles', category: 'food_item', level: 0, sceneContext: 'written on the menu board', visualCue: 'stack of instant noodle packets behind the counter' },
  { word: '순대', romanization: 'sundae', translation: 'blood sausage', category: 'food_item', level: 0, sceneContext: 'on the menu board next to 떡볶이', visualCue: 'dark sausage slices on a plate with salt' },
  // Level 2 - vocabulary
  { word: '김밥', romanization: 'gimbap', translation: 'seaweed rice roll', category: 'food_item', level: 2, sceneContext: 'sliced rolls displayed in the glass case at the front', visualCue: 'colorful cross-sections of seaweed-wrapped rice rolls' },
  { word: '어묵', romanization: 'eomuk', translation: 'fish cake (formal)', category: 'food_item', level: 2, sceneContext: 'ajusshi uses this word instead of 오뎅 sometimes' },
  { word: '만두', romanization: 'mandu', translation: 'dumplings', category: 'food_item', level: 2, sceneContext: 'steaming in a bamboo basket on the side', visualCue: 'plump dumplings with steam rising from bamboo steamer' },
  { word: '튀김', romanization: 'twigim', translation: 'deep-fried snacks', category: 'food_item', level: 2, sceneContext: 'frying in oil', visualCue: 'golden fried vegetables and shrimp draining on paper' },
  { word: '꼬치', romanization: 'kkochi', translation: 'skewers', category: 'food_item', level: 2, sceneContext: 'a rack of skewers on the counter', visualCue: 'wooden skewers with meat and vegetables lined up in a row' },
  { word: '호떡', romanization: 'hotteok', translation: 'sweet pancake', category: 'food_item', level: 2, sceneContext: 'pressed flat on the griddle', visualCue: 'golden-brown pancake being pressed flat, sweet filling oozing' },
  { word: '붕어빵', romanization: 'bungeoppang', translation: 'fish-shaped bread', category: 'food_item', level: 2, sceneContext: 'a neighboring cart sells these', visualCue: 'fish-shaped waffle filled with red bean paste' },
  { word: '비빔밥', romanization: 'bibimbap', translation: 'mixed rice', category: 'food_item', level: 2, sceneContext: 'not on this menu — you hear others ordering it nearby' },
  { word: '볶음밥', romanization: 'bokkeumbap', translation: 'fried rice', category: 'food_item', level: 2, sceneContext: 'ajusshi makes this with leftover 떡볶이 sauce at the end' },
  { word: '김치', romanization: 'gimchi', translation: 'kimchi', category: 'food_item', level: 2, sceneContext: 'free side dish — ajusshi puts it on the counter without asking' },
  { word: '물', romanization: 'mul', translation: 'water', category: 'drink', level: 2, sceneContext: 'you ask for this when the 떡볶이 is too spicy' },
  { word: '콜라', romanization: 'kolla', translation: 'cola', category: 'drink', level: 2, sceneContext: 'in the mini fridge under the counter' },
  { word: '주스', romanization: 'juseu', translation: 'juice', category: 'drink', level: 2, sceneContext: 'in the mini fridge' },
  { word: '소주', romanization: 'soju', translation: 'soju', category: 'drink', level: 2, sceneContext: 'Jin offers you a glass after practice' },
  { word: '맥주', romanization: 'maekju', translation: 'beer', category: 'drink', level: 2, sceneContext: 'senior trainees order this, ajusshi teases you about age' },
  { word: '사이다', romanization: 'saida', translation: 'cider/sprite', category: 'drink', level: 2 },
  // Taste words
  { word: '맵다', romanization: 'maepda', translation: 'spicy', category: 'taste', level: 2 },
  { word: '달다', romanization: 'dalda', translation: 'sweet', category: 'taste', level: 2 },
  { word: '짜다', romanization: 'jjada', translation: 'salty', category: 'taste', level: 2 },
  { word: '맛있다', romanization: 'masitda', translation: 'delicious', category: 'taste', level: 2 },
  { word: '맛없다', romanization: 'maseopda', translation: 'not tasty', category: 'taste', level: 2 },
  // Numbers
  { word: '하나', romanization: 'hana', translation: 'one', category: 'number', level: 2 },
  { word: '둘', romanization: 'dul', translation: 'two', category: 'number', level: 2 },
  { word: '셋', romanization: 'set', translation: 'three', category: 'number', level: 2 },
  { word: '넷', romanization: 'net', translation: 'four', category: 'number', level: 2 },
  { word: '다섯', romanization: 'daseot', translation: 'five', category: 'number', level: 2 },
  // Verbs
  { word: '먹다', romanization: 'meokda', translation: 'to eat', category: 'verb', level: 2 },
  { word: '주다', romanization: 'juda', translation: 'to give', category: 'verb', level: 2 },
  { word: '마시다', romanization: 'masida', translation: 'to drink', category: 'verb', level: 2 },
  { word: '사다', romanization: 'sada', translation: 'to buy', category: 'verb', level: 2 },
  { word: '시키다', romanization: 'sikida', translation: 'to order', category: 'verb', level: 2 },
  // Courtesy
  { word: '주세요', romanization: 'juseyo', translation: 'please (give me)', category: 'courtesy', level: 2 },
  { word: '감사합니다', romanization: 'gamsahamnida', translation: 'thank you', category: 'courtesy', level: 2 },
  { word: '잠시만요', romanization: 'jamsimanyo', translation: 'just a moment', category: 'courtesy', level: 2 },
  { word: '여기요', romanization: 'yeogiyo', translation: 'excuse me (here)', category: 'courtesy', level: 2 },
  { word: '얼마예요', romanization: 'eolmayeyo', translation: 'how much?', category: 'courtesy', level: 2 },
];

export const GRAMMAR_TARGETS: GrammarTarget[] = [
  {
    id: 'ko-gram-juseyo',
    pattern: 'N + 주세요',
    explanation: 'Add 주세요 after a noun to politely ask for something. Like saying "please give me [noun]".',
    examples: [
      { target: '떡볶이 주세요', translation: 'Tteokbokki, please' },
      { target: '물 주세요', translation: 'Water, please' },
      { target: '라면 주세요', translation: 'Ramyeon, please' },
    ],
    level: 3,
    locationId: 'pojangmacha',
  },
  {
    id: 'ko-gram-object-particle',
    pattern: '을/를',
    explanation: 'Object particle: 을 after consonant-ending nouns, 를 after vowel-ending nouns. Marks what you\'re doing the action to.',
    examples: [
      { target: '떡볶이를 먹다', translation: 'to eat tteokbokki' },
      { target: '라면을 먹다', translation: 'to eat ramyeon' },
      { target: '물을 마시다', translation: 'to drink water' },
    ],
    level: 3,
    locationId: 'pojangmacha',
  },
  {
    id: 'ko-gram-counters',
    pattern: 'N + 개',
    explanation: 'Use native Korean numbers + counter 개 for general items. 한 개, 두 개, 세 개...',
    examples: [
      { target: '떡볶이 두 개 주세요', translation: 'Two tteokbokki, please' },
      { target: '만두 세 개 주세요', translation: 'Three dumplings, please' },
    ],
    level: 3,
    locationId: 'pojangmacha',
  },
];

export const POJANGMACHA: Location = {
  id: 'pojangmacha',
  cityId: 'seoul',
  name: { en: 'Street Food Stall', ko: '포장마차' },
  domain: 'food',
  order: 1,
  backgroundImageUrl: '/assets/backgrounds/pojangmacha.png',
  ambientDescription:
    'A lively 포장마차 tent near Hongdae. Steam rises from bubbling pots of 떡볶이 and 어묵. Orange plastic stools, a handwritten menu board, and the sound of sizzling oil. Ajusshi wipes the counter with a practiced hand. Other trainees drift in and out.',
  levels: [
    {
      level: 0,
      name: 'SCRIPT',
      description: 'Can I recognise the symbols?',
      objectives: LEVEL_0_OBJECTIVES,
      estimatedSessionMinutes: 15,
      assessmentCriteria: { minAccuracy: 0.8, minItemsCompleted: 20, requiredObjectives: ['ko-script-consonants-basic', 'ko-script-vowels-basic'] },
    },
    {
      level: 1,
      name: 'PRONUNCIATION',
      description: 'Can I say them correctly?',
      objectives: LEVEL_1_OBJECTIVES,
      estimatedSessionMinutes: 18,
      assessmentCriteria: { minAccuracy: 0.75, minItemsCompleted: 15, requiredObjectives: ['ko-pron-jamo-all'] },
    },
    {
      level: 2,
      name: 'VOCABULARY',
      description: 'Do I know what they mean?',
      objectives: LEVEL_2_OBJECTIVES,
      estimatedSessionMinutes: 20,
      assessmentCriteria: { minAccuracy: 0.8, minItemsCompleted: 30, requiredObjectives: ['ko-vocab-food-items', 'ko-vocab-courtesy'] },
    },
    {
      level: 3,
      name: 'GRAMMAR',
      description: 'Can I build sentences?',
      objectives: LEVEL_3_OBJECTIVES,
      estimatedSessionMinutes: 20,
      assessmentCriteria: { minAccuracy: 0.8, minItemsCompleted: 10, requiredObjectives: ['ko-gram-juseyo'] },
    },
  ],
  vocabularyTargets: VOCABULARY_TARGETS,
  grammarTargets: GRAMMAR_TARGETS,
};
